package Dao;
// Generated 10/08/2021 19:45:35 by Hibernate Tools 4.3.1



/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private String email;
     private String actividad;

    public Personal() {
    }

	
    public Personal(int id) {
        this.id = id;
    }
    public Personal(int id, String nombre, String apellido, String email, String actividad) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.actividad = actividad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }




}


